# workflow name
name: Generate release-artifacts

# on tags
on:
  push:
    tags:
      - "v*.*.*"

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: "darwin/amd64, darwin/arm64, windows/arm64"
          package: ""
          name: "dockercraft"
          compress: "false"
          dest: "dist"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dockercraft-darwin-amd64
            dockercraft-darwin-arm64
            dockercraft-windows-arm64.exe
